package com.ai_model_hub.demo.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Mode (M3 Blue) ──────────────────────────────────────────────
val LightPrimary = Color(0xFF00497D)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF0061A4)
val LightOnPrimaryContainer = Color(0xFFC0DBFF)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F8)
val LightOnSecondaryContainer = Color(0xFF596576)
val LightBackground = Color(0xFFF8F9FF)
val LightSurface = Color(0xFFF8F9FF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF2F3FA)
val LightSurfaceContainer = Color(0xFFECEEF4)
val LightSurfaceContainerHigh = Color(0xFFE6E8EE)
val LightSurfaceContainerHighest = Color(0xFFE1E2E8)
val LightOnSurface = Color(0xFF191C20)
val LightOnSurfaceVariant = Color(0xFF414750)
val LightOutline = Color(0xFF717782)
val LightOutlineVariant = Color(0xFFC1C7D2)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// ── Dark Mode (M3 Blue Deep Navy) ─────────────────────────────────────
val DarkPrimary = Color(0xFF9FCAFF)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFFD1E4FF)
val DarkOnPrimaryContainer = Color(0xFF001D36)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF253140)
val DarkSecondaryContainer = Color(0xFF3C4858)
val DarkOnSecondaryContainer = Color(0xFFD7E3F8)
val DarkBackground = Color(0xFF0B1326)
val DarkSurface = Color(0xFF0B1326)
val DarkSurfaceContainerLowest = Color(0xFF060E20)
val DarkSurfaceContainerLow = Color(0xFF131B2E)
val DarkSurfaceContainer = Color(0xFF171F32)
val DarkSurfaceContainerHigh = Color(0xFF1B2336)
val DarkSurfaceContainerHighest = Color(0xFF252D41)
val DarkOnSurface = Color(0xFFE1E2E8)
val DarkOnSurfaceVariant = Color(0xFFC1C7D2)
val DarkOutline = Color(0xFF8B919E)
val DarkOutlineVariant = Color(0xFF414750)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
