package com.ai_model_hub.demo.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Mode (M3 Teal — seed #00796B) ──────────────────────────────
val LightPrimary = Color(0xFF006A60)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9EF2E4)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF4A6360)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E5)
val LightOnSecondaryContainer = Color(0xFF051F1D)
val LightTertiary = Color(0xFF00639B)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC2E7FF)
val LightOnTertiaryContainer = Color(0xFF001E31)
val LightBackground = Color(0xFFF5FAFA)
val LightSurface = Color(0xFFF5FAFA)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEEF4F4)
val LightSurfaceContainer = Color(0xFFE9EFEF)
val LightSurfaceContainerHigh = Color(0xFFE3E9E9)
val LightSurfaceContainerHighest = Color(0xFFDDE3E3)
val LightOnSurface = Color(0xFF171D1C)
val LightOnSurfaceVariant = Color(0xFF3F4946)
val LightOutline = Color(0xFF6F7976)
val LightOutlineVariant = Color(0xFFBEC9C6)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// ── Dark Mode (M3 Teal — seed #00796B) ───────────────────────────────
val DarkPrimary = Color(0xFF82D9CB)
val DarkOnPrimary = Color(0xFF003731)
val DarkPrimaryContainer = Color(0xFF005048)
val DarkOnPrimaryContainer = Color(0xFF9EF2E4)
val DarkSecondary = Color(0xFFB1CCCA)
val DarkOnSecondary = Color(0xFF1C3432)
val DarkSecondaryContainer = Color(0xFF324B48)
val DarkOnSecondaryContainer = Color(0xFFCCE8E5)
val DarkTertiary = Color(0xFF7FCFFF)
val DarkOnTertiary = Color(0xFF003355)
val DarkTertiaryContainer = Color(0xFF004A77)
val DarkOnTertiaryContainer = Color(0xFFC2E7FF)
val DarkBackground = Color(0xFF0E1514)
val DarkSurface = Color(0xFF0E1514)
val DarkSurfaceContainerLowest = Color(0xFF09100F)
val DarkSurfaceContainerLow = Color(0xFF171D1C)
val DarkSurfaceContainer = Color(0xFF1B2120)
val DarkSurfaceContainerHigh = Color(0xFF252B2A)
val DarkSurfaceContainerHighest = Color(0xFF303635)
val DarkOnSurface = Color(0xFFDDE3E3)
val DarkOnSurfaceVariant = Color(0xFFBEC9C6)
val DarkOutline = Color(0xFF899390)
val DarkOutlineVariant = Color(0xFF3F4946)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
